[workspace]
channels = ["conda-forge", "pytorch"]
name = "rag_hyde"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
faiss-cpu = "*"
transformers = "*"
jupyter = "*"
ruff = "*"
rich = "*"
gradio = "*"
pre-commit = ">=4.3.0,<5"

[feature.linux]
platforms = ["linux-64"]
system-requirements = { cuda = "12.0" }
dependencies = { python = "3.12.*" }

[feature.mac]
platforms = ["osx-arm64"]
dependencies = { python = "3.12.*" }

[feature.mac.pypi-dependencies]
torch = "*"
torchvision = "*"
mlx-lm = "*"

[feature.linux.pypi-dependencies]
torch = { version = "*", index = "https://download.pytorch.org/whl/cu129" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu129" }
faiss-gpu-cu12 = "*"
autoawq = "*"

[environments]
linux = ["linux"]
mac = ["mac"]

[pypi-dependencies]
sentence-transformers = "*"
langchain-text-splitters = "*"
pymupdf = "*"
pymupdf4llm = "*"
pypdfium2 = "*"
docling = ">=2.55.1, <3"
# docling = "*"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]
